# Generated by Django 6.0.7 on 2026-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restorationcertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='NC', max_length=2)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Restoration Service Area',
                'verbose_name_plural': 'Restoration Service Areas',
                'ordering': ['order', 'city'],
            },
        ),
    ]
