# Generated by Django 6.0.7 on 2026-07-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restorationservicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.restorationservice')),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.restorationservicearea')),
            ],
            options={
                'verbose_name': 'Restoration Review',
                'verbose_name_plural': 'Restoration Reviews',
                'ordering': ['-id'],
            },
        ),
    ]
