# Generated by Django 6.0.7 on 2026-07-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restorationreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restorationreview',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restorationreview',
            name='location',
        ),
    ]
