# Generated by Django 6.0.7 on 2026-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_restorationreview_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restoration_team')),
                ('team_member', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Restoration Team',
                'ordering': ['order', 'team_member', 'occupation'],
            },
        ),
    ]
