# Generated by Django 6.0.7 on 2026-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_restorationteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorationteam',
            name='team_member',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
