# Generated by Django 6.0.7 on 2026-08-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_restorationteam_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to='restoration_projects/before/')),
                ('after_image', models.ImageField(upload_to='restoration_projects/after/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.restorationservice')),
            ],
            options={
                'verbose_name': 'Restoration Projects',
                'verbose_name_plural': 'Restoration Projects',
                'ordering': ['before_image', 'after_image', 'title', 'alt_text', 'caption', 'description'],
            },
        ),
    ]
