# Generated by Django 6.0.7 on 2026-08-21 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_restorationproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restorationproject',
            options={'verbose_name': 'Restoration Projects', 'verbose_name_plural': 'Restoration Projects'},
        ),
        migrations.RemoveField(
            model_name='restorationproject',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='restorationproject',
            name='after_alt_txt',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='restorationproject',
            name='before_alt_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='restorationproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restorationservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
