# Generated by Django 6.0.7 on 2026-08-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_restorationproject_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restorationservice',
            name='slug',
        ),
    ]
