# Generated by Django 6.0.7 on 2026-08-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_restorationservice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationservice',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
