# Generated by Django 6.0.7 on 2026-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_restorationservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorationservice',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
