# Generated by Django 6.0.4 on 2026-09-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_restorationservice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('body', models.TextField(blank=True)),
                ('source_author', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.restorationservice')),
            ],
            options={
                'verbose_name_plural': 'Restoration Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
