# Generated by Django 6.0.4 on 2026-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_restorationpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
