# Generated by Django 6.0.4 on 2026-09-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_restorationpost_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restorationpost',
            old_name='service',
            new_name='related_service',
        ),
    ]
