# Generated by Django 6.0.4 on 2026-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_service_restorationpost_related_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorationpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
