# Generated by Django 6.0.4 on 2026-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_restorationpost_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restorationpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name_plural': 'Restoration Blog Posts'},
        ),
        migrations.RemoveField(
            model_name='restorationpost',
            name='body',
        ),
        migrations.RemoveField(
            model_name='restorationpost',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='restorationpost',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='restorationpost',
            name='source_author',
        ),
        migrations.RemoveField(
            model_name='restorationpost',
            name='source_url',
        ),
        migrations.AddField(
            model_name='restorationpost',
            name='author',
            field=models.CharField(default='StaDry Restorations', max_length=200),
        ),
        migrations.AddField(
            model_name='restorationpost',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restorationpost',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restorationpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restorationpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restorationpost',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
