# Generated by Django 6.0.7 on 2026-09-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_restorationpost_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestorationPost',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name_plural': 'Posts'},
        ),
    ]
