# Generated by Django 6.0.7 on 2026-09-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_restorationpost_post_alter_post_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestorationCarouselBackground',
            new_name='CarouselBackground',
        ),
        migrations.RenameModel(
            old_name='RestorationCertification',
            new_name='Certification',
        ),
        migrations.RenameModel(
            old_name='RestorationProject',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='RestorationReview',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='RestorationService',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='RestorationServiceArea',
            new_name='ServiceArea',
        ),
        migrations.RenameModel(
            old_name='RestorationSiteSetting',
            new_name='SiteSetting',
        ),
        migrations.RenameModel(
            old_name='RestorationTeam',
            new_name='Team',
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['title'], 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['order', 'city'], 'verbose_name_plural': 'Service Areas'},
        ),
    ]
