# Generated by Django 6.0.7 on 2026-09-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_restorationcarouselbackground_carouselbackground_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselbackground',
            options={'ordering': ['order'], 'verbose_name': 'Carousel Background'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order', 'team_member', 'occupation'], 'verbose_name': 'Team'},
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='service', help_text='Icon needed', max_length=100),
        ),
    ]
